# Generated by Django 5.2.13 on 2026-04-19 07:14

import django.db.models.deletion
import querry.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('video', models.FileField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('voice', models.FileField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_queries', to=settings.AUTH_USER_MODEL)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='querry.mediamessage')),
            ],
        ),
        migrations.CreateModel(
            name='MediaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('video', models.FileField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('voice', models.FileField(blank=True, null=True, upload_to=querry.models.temp_upload_path, validators=[querry.models.validate_file_size_20mb])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='querry.mediamessage')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
