# Generated by Django 5.2.13 on 2026-04-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelIndexCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(max_length=10)),
                ('bbox_hash', models.CharField(max_length=64)),
                ('bbox', models.JSONField()),
                ('date', models.DateField()),
                ('image_base64', models.TextField()),
                ('statistics', models.JSONField()),
                ('audio_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.farms')),
            ],
            options={
                'unique_together': {('index_type', 'bbox_hash', 'date', 'farm_id')},
            },
        ),
    ]
