# Generated by Django 5.2.13 on 2026-04-19 09:41

import Reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CropsRecomendations', '0001_initial'),
        ('User', '0002_farms_crop_farms_crop_season_farms_sowing_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=Reports.models.report_upload_path)),
                ('is_successful', models.BooleanField(default=True)),
                ('crop_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_crop_season', to='CropsRecomendations.cropseason')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_crop_type', to='CropsRecomendations.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_farms', to='User.farms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
