# Generated by Django 5.2.12 on 2026-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FAILED', 'Failed'), ('DONE', 'Done')], default='STARTED', max_length=20),
        ),
    ]
