# Generated by Django 5.2.12 on 2026-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_reports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_type',
            field=models.CharField(choices=[('FARMER', 'farmer'), ('AGRO', 'agro')], default='FARMER', max_length=50),
        ),
    ]
