# Generated by Django 5.2.13 on 2026-04-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CropsRecomendations.croptype'),
        ),
        migrations.AddField(
            model_name='farms',
            name='crop_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CropsRecomendations.cropseason'),
        ),
        migrations.AddField(
            model_name='farms',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
