# Generated by Django 5.2.12 on 2026-04-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedValues', '0001_initial'),
        ('User', '0002_farms_crop_farms_crop_season_farms_sowing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LinkedValues.districts'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
