# Generated by Django 5.2.13 on 2026-04-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_types', to='CropsRecomendations.cropseason')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('harvesting_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropsRecomendations.croptype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CropsRecomendations.cropseason')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(choices=[('NDVI', 'NDVI'), ('NDMI', 'NDMI'), ('SAVI', 'SAVI'), ('MSAVI', 'MSAVI'), ('RECL', 'RECL'), ('NDRE', 'NDRE')], max_length=10)),
                ('crop_stage', models.CharField(choices=[('pre_sowing', 'Pre Sowing'), ('sowing', 'Sowing'), ('germination', 'Germination'), ('four_leaf_stage', 'Four Leaf Stage'), ('square_formation', 'Square Formation'), ('flowering', 'Flowering'), ('bolls_formation', 'Bolls Formation'), ('picking', 'Picking')], max_length=50)),
                ('starting_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('ending_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('zone', models.CharField(choices=[('green', 'Green'), ('light_green', 'Light Green'), ('yellow', 'Yellow'), ('purple', 'Purple')], max_length=20)),
                ('recommendation_text', models.TextField()),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CropsRecomendations.recommendation')),
            ],
        ),
    ]
