# Generated by Django 5.2.12 on 2026-04-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0001_initial'),
        ('LinkedValues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationitem',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LinkedValues.districts'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('season', 'crop', 'sowing_month', 'harvesting_month'), name='unique_recommendation_per_crop_season_range'),
        ),
    ]
