# Generated by Django 5.2.12 on 2026-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0002_recommendationitem_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationitem',
            name='crop_stage',
            field=models.CharField(choices=[('pre_planting_early', 'Pre Planting (Early Growth)'), ('vegetative_growth', 'Vegetative Growth'), ('flowering_reproductive', 'Flowering/Reproductive'), ('maturity_pre_harvest', 'Maturity/Pre-Harvest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendationitem',
            name='indice',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('MSAVI', 'MSAVI'), ('NDRE', 'NDRE'), ('ReCL', 'ReCL'), ('NDMI', 'NDMI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendationitem',
            name='zone',
            field=models.CharField(choices=[('green', 'Green'), ('light_green', 'Light Green'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='purple', max_length=20),
        ),
    ]
