# Generated by Django 5.2.12 on 2026-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0003_alter_recommendationitem_crop_stage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recommendation',
            name='unique_recommendation_per_crop_season_range',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='harvesting_month',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='sowing_month',
        ),
        migrations.RemoveField(
            model_name='recommendationitem',
            name='district',
        ),
        migrations.RemoveField(
            model_name='recommendationitem',
            name='ending_month',
        ),
        migrations.RemoveField(
            model_name='recommendationitem',
            name='starting_month',
        ),
        migrations.RemoveField(
            model_name='recommendationitem',
            name='zone',
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='duration_in_days',
            field=models.TextField(default='[0-30]'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('season', 'crop'), name='unique_recommendation_per_crop_season_range'),
        ),
    ]
