# Generated by Django 5.2.12 on 2026-04-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0004_remove_recommendation_unique_recommendation_per_crop_season_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationitem',
            name='duration_in_days',
            field=models.CharField(default='[0-30]', max_length=500),
        ),
    ]
