# Generated by Django 6.0.2 on 2026-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropsRecomendations', '0005_alter_recommendationitem_duration_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationitem',
            name='duration_in_days',
            field=models.CharField(default='0-30', max_length=500),
        ),
    ]
